// automatically generated by the FlatBuffers compiler, do not modify
// @generated

extern crate alloc;

#[allow(unused_imports, dead_code)]
pub mod sensors {

extern crate alloc;

pub enum PayloadOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Payload<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Payload<'a> {
  type Inner = Payload<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Payload<'a> {
  pub const VT_LAT: ::flatbuffers::VOffsetT = 4;
  pub const VT_LON: ::flatbuffers::VOffsetT = 6;
  pub const VT_ALT: ::flatbuffers::VOffsetT = 8;
  pub const VT_BATTERY_PERC: ::flatbuffers::VOffsetT = 10;
  pub const VT_TIMESTAMP: ::flatbuffers::VOffsetT = 12;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Payload { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args PayloadArgs
  ) -> ::flatbuffers::WIPOffset<Payload<'bldr>> {
    let mut builder = PayloadBuilder::new(_fbb);
    builder.add_timestamp(args.timestamp);
    builder.add_alt(args.alt);
    builder.add_lon(args.lon);
    builder.add_lat(args.lat);
    builder.add_battery_perc(args.battery_perc);
    builder.finish()
  }


  #[inline]
  pub fn lat(&self) -> f64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f64>(Payload::VT_LAT, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn lon(&self) -> f64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f64>(Payload::VT_LON, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn alt(&self) -> f64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f64>(Payload::VT_ALT, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn battery_perc(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(Payload::VT_BATTERY_PERC, Some(0)).unwrap()}
  }
  #[inline]
  pub fn timestamp(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Payload::VT_TIMESTAMP, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for Payload<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<f64>("lat", Self::VT_LAT, false)?
     .visit_field::<f64>("lon", Self::VT_LON, false)?
     .visit_field::<f64>("alt", Self::VT_ALT, false)?
     .visit_field::<u8>("battery_perc", Self::VT_BATTERY_PERC, false)?
     .visit_field::<u64>("timestamp", Self::VT_TIMESTAMP, false)?
     .finish();
    Ok(())
  }
}
pub struct PayloadArgs {
    pub lat: f64,
    pub lon: f64,
    pub alt: f64,
    pub battery_perc: u8,
    pub timestamp: u64,
}
impl<'a> Default for PayloadArgs {
  #[inline]
  fn default() -> Self {
    PayloadArgs {
      lat: 0.0,
      lon: 0.0,
      alt: 0.0,
      battery_perc: 0,
      timestamp: 0,
    }
  }
}

pub struct PayloadBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> PayloadBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_lat(&mut self, lat: f64) {
    self.fbb_.push_slot::<f64>(Payload::VT_LAT, lat, 0.0);
  }
  #[inline]
  pub fn add_lon(&mut self, lon: f64) {
    self.fbb_.push_slot::<f64>(Payload::VT_LON, lon, 0.0);
  }
  #[inline]
  pub fn add_alt(&mut self, alt: f64) {
    self.fbb_.push_slot::<f64>(Payload::VT_ALT, alt, 0.0);
  }
  #[inline]
  pub fn add_battery_perc(&mut self, battery_perc: u8) {
    self.fbb_.push_slot::<u8>(Payload::VT_BATTERY_PERC, battery_perc, 0);
  }
  #[inline]
  pub fn add_timestamp(&mut self, timestamp: u64) {
    self.fbb_.push_slot::<u64>(Payload::VT_TIMESTAMP, timestamp, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> PayloadBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    PayloadBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Payload<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Payload<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Payload");
      ds.field("lat", &self.lat());
      ds.field("lon", &self.lon());
      ds.field("alt", &self.alt());
      ds.field("battery_perc", &self.battery_perc());
      ds.field("timestamp", &self.timestamp());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `Payload`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_payload_unchecked`.
pub fn root_as_payload(buf: &[u8]) -> Result<Payload<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<Payload>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Payload` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_payload_unchecked`.
pub fn size_prefixed_root_as_payload(buf: &[u8]) -> Result<Payload<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<Payload>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Payload` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_payload_unchecked`.
pub fn root_as_payload_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Payload<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<Payload<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Payload` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_payload_unchecked`.
pub fn size_prefixed_root_as_payload_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Payload<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<Payload<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Payload and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Payload`.
pub unsafe fn root_as_payload_unchecked(buf: &[u8]) -> Payload<'_> {
  unsafe { ::flatbuffers::root_unchecked::<Payload>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Payload and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Payload`.
pub unsafe fn size_prefixed_root_as_payload_unchecked(buf: &[u8]) -> Payload<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<Payload>(buf) }
}
#[inline]
pub fn finish_payload_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<Payload<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_payload_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<Payload<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod sensors

